# Generated by Django 5.0.4 on 2026-04-22 14:41

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawmatch_api', '0004_alter_pet_animal'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pawmatch_api.animal'),
        ),
    ]
